name: Fetch KAMIS EcoPriceList

on:
  schedule:
    - cron: '*/10 * * * *' # 매 10분마다 실행

jobs:
  fetch_eco_price_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Eco Price List
        env:
          KAMIS_API_KEY: ${{ secrets.KAMIS_KEY }}
        run: |
          # API 요청을 통해 JSON 파일로 저장
          curl -X GET "http://www.kamis.or.kr/service/price/xml.do?action=EcoPriceList&apikey=${KAMIS_KEY}&p_cert_key=${KAMIS_API_KEY}&p_cert_id=인증아이디&price_type=0&p_returntype=json" -o eco_price_list.json

          # acebucks/docs 디렉터리로 파일 이동
          mkdir -p acebucks/docs
          mv eco_price_list.json acebucks/docs/eco_price_list.json

      - name: Commit and Push JSON File
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add acebucks/docs/eco_price_list.json
          git commit -m 'Add latest eco price list'
          git push
