name: Fetch KAMIS EcoPriceList

on:
  schedule:
    - cron: '*/15 * * * *' # 매 15분마다 실행

jobs:
  fetch_eco_price_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Eco Price List
        env:
          KAMIS_KEY: ${{ secrets.KAMIS_KEY }}  # 올바른 변수 사용
          P_CERT_ID: ${{ secrets.P_CERT_ID }}
          
        run: |
          # API 요청을 통해 JSON 파일로 저장
          curl -w "%{http_code}\n" -X GET "http://www.example.com" -o output.json

          # acebucks/docs 디렉터리로 파일 이동
          mkdir -p acebucks/docs
          mv eco_price_list.json acebucks/docs/eco_price_list.json

      - name: Commit and Push JSON File
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add acebucks/docs/eco_price_list.json
          git commit -m 'Update eco price list every 10 minutes'
          git push
